/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lab411_eeg_filedata_FileData */

#ifndef _Included_lab411_eeg_filedata_FileData
#define _Included_lab411_eeg_filedata_FileData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lab411_eeg_filedata_FileData
 * Method:    writeFiledata
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_lab411_eeg_filedata_FileData_writeFiledata
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     lab411_eeg_filedata_FileData
 * Method:    readDataFileOutput
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_lab411_eeg_filedata_FileData_readDataFileOutput
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
