/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lab411_eeg_gazeservice_Calculate */

#ifndef _Included_lab411_eeg_gazeservice_Calculate
#define _Included_lab411_eeg_gazeservice_Calculate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lab411_eeg_gazeservice_Calculate
 * Method:    getmean
 * Signature: ([IIIDDD)D
 */
JNIEXPORT jdouble JNICALL Java_lab411_eeg_gazeservice_Calculate_getmean
  (JNIEnv *, jclass, jintArray, jint, jint, jdouble, jdouble, jdouble);

/*
 * Class:     lab411_eeg_gazeservice_Calculate
 * Method:    gethfd
 * Signature: ([DI)D
 */
JNIEXPORT jdouble JNICALL Java_lab411_eeg_gazeservice_Calculate_gethfd
  (JNIEnv *, jclass, jdoubleArray, jint);

/*
 * Class:     lab411_eeg_gazeservice_Calculate
 * Method:    getYnFilter
 * Signature: ([IIIDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_lab411_eeg_gazeservice_Calculate_getYnFilter
  (JNIEnv *, jclass, jintArray, jint, jint, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
