/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class la411_eeg_svm_SVM */

#ifndef _Included_la411_eeg_svm_SVM
#define _Included_la411_eeg_svm_SVM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     la411_eeg_svm_SVM
 * Method:    trainClassifier
 * Signature: (Ljava/lang/String;IIFILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_la411_eeg_svm_SVM_trainClassifier
  (JNIEnv *, jclass, jstring, jint, jint, jfloat, jint, jstring);

/*
 * Class:     la411_eeg_svm_SVM
 * Method:    doClassification
 * Signature: (ILjava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_la411_eeg_svm_SVM_doClassification
  (JNIEnv *, jclass, jint, jstring, jstring, jstring);


#ifdef __cplusplus
}
#endif
#endif
