/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <opencv2/core/core.hpp>

char* grid[] = { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L",
		"M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",
		"1", "2", "3", "4", "5", "6", "7", "8", "9", "0" };

/* Header for class com_lab411_classifiertrainer_MainProcess */

#ifndef _Included_com_lab411_classifiertrainer_MainProcess
#define _Included_com_lab411_classifiertrainer_MainProcess
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_lab411_classifiertrainer_MainProcess
 * Method:    CalculateTraining
 * Signature: (II[D[I[DI)Z
 */JNIEXPORT jboolean JNICALL Java_com_lab411_classifiertrainer_MainProcess_CalculateTraining(
		JNIEnv *, jclass, jint, jint, jdoubleArray, jintArray, jdoubleArray,
		jint, jstring);

/*
 * Class:     com_lab411_classifiertrainer_MainProcess
 * Method:    TestTrain
 * Signature: ([D[I[DZZI)V
 */JNIEXPORT jdouble JNICALL Java_com_lab411_classifiertrainer_MainProcess_TestTrain(
		JNIEnv *, jclass, jdoubleArray, jintArray, jdoubleArray, jboolean,
		jboolean, jint, jstring);
#ifdef __cplusplus
}
#endif
#endif
