/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_filter_MainProcess */

#ifndef _Included_com_example_filter_MainProcess
#define _Included_com_example_filter_MainProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_filter_MainProcess
 * Method:    xDawn
 * Signature: ([[DD)I
 */
JNIEXPORT jint JNICALL Java_com_example_openvibeforandroid_XdawnTrainer_xDawn
  (JNIEnv *, jclass, jobjectArray, jdouble);

/*
 * Class:     com_example_filter_MainProcess
 * Method:    getValues
 * Signature: ([[D)I
 */
JNIEXPORT jint JNICALL Java_com_example_openvibeforandroid_XdawnTrainer_getValues
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     com_example_filter_MainProcess
 * Method:    calculateXDawn
 * Signature: ([[D[[D)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_com_example_openvibeforandroid_XdawnTrainer_calculateXDawn
  (JNIEnv *, jclass, jobjectArray, jobjectArray);

/*
 * Class:     com_example_filter_MainProcess
 * Method:    xDawnProcess
 * Signature: ([[D[[D[DDI)I
 */
JNIEXPORT jint JNICALL Java_com_example_openvibeforandroid_XdawnTrainer_xDawnProcess
  (JNIEnv *, jclass, jobjectArray, jobjectArray, jintArray, jdouble, jint);

#ifdef __cplusplus
}
#endif
#endif
