/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_lab411_votingclassifier_MainProcess */

#ifndef _Included_com_lab411_votingclassifier_MainProcess
#define _Included_com_lab411_votingclassifier_MainProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lab411_votingclassifier_MainProcess
 * Method:    Process
 * Signature: (Ljava/util/ArrayList;[D)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_lab411_votingclassifier_MainProcess_Process__Ljava_util_ArrayList_2_3D
  (JNIEnv *, jclass, jobject, jdoubleArray);

int labelRow;
int labelCol;
#ifdef __cplusplus
}
#endif
#endif
