/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#define SAMPLECOUNTPERERP 19
#define CHANNEL 3
#define FEATURECOUNT 144
#define SIZE 57
/* Header for class com_lab411_featureaggregator_MainProcess */

#ifndef _Included_com_lab411_featureaggregator_MainProcess
#define _Included_com_lab411_featureaggregator_MainProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_lab411_featureaggregator_MainProcess
 * Method:    FeatureAggregator
 * Signature: (Ljava/util/List;Ljava/util/List;)[Lcom/lab411/featureaggregator/FeatureVector;
 */
JNIEXPORT jobjectArray JNICALL Java_com_lab411_featureaggregator_MainProcess_FeatureAggregator
  (JNIEnv *, jclass, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
