/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class la411_eeg_svm_Feature */

#ifndef _Included_la411_eeg_svm_Feature
#define _Included_la411_eeg_svm_Feature
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     la411_eeg_svm_Feature
 * Method:    Root_Mean_Square
 * Signature: (I[F)F
 */
JNIEXPORT jfloat JNICALL Java_la411_eeg_svm_Feature_Root_1Mean_1Square
  (JNIEnv *, jclass, jint, jfloatArray);

/*
 * Class:     la411_eeg_svm_Feature
 * Method:    Simple_Square_Integral
 * Signature: (I[F)F
 */
JNIEXPORT jfloat JNICALL Java_la411_eeg_svm_Feature_Simple_1Square_1Integral
  (JNIEnv *, jclass, jint, jfloatArray);

/*
 * Class:     la411_eeg_svm_Feature
 * Method:    Waveform_Length
 * Signature: (I[F)F
 */
JNIEXPORT jfloat JNICALL Java_la411_eeg_svm_Feature_Waveform_1Length
  (JNIEnv *, jclass, jint, jfloatArray);

/*
 * Class:     la411_eeg_svm_Feature
 * Method:    Mean_Absolute_Value
 * Signature: (I[F)F
 */
JNIEXPORT jfloat JNICALL Java_la411_eeg_svm_Feature_Mean_1Absolute_1Value
  (JNIEnv *, jclass, jint, jfloatArray);

/*
 * Class:     la411_eeg_svm_Feature
 * Method:    Modified_Mean_Absolute_Value_1
 * Signature: (I[F)F
 */
JNIEXPORT jfloat JNICALL Java_la411_eeg_svm_Feature_Modified_1Mean_1Absolute_1Value_11
  (JNIEnv *, jclass, jint, jfloatArray);

/*
 * Class:     la411_eeg_svm_Feature
 * Method:    Modified_Mean_Absolute_Value_2
 * Signature: (I[F)F
 */
JNIEXPORT jfloat JNICALL Java_la411_eeg_svm_Feature_Modified_1Mean_1Absolute_1Value_12
  (JNIEnv *, jclass, jint, jfloatArray);

/*
 * Class:     la411_eeg_svm_Feature
 * Method:    Slope_Sign_Change
 * Signature: (I[FF)F
 */
JNIEXPORT jfloat JNICALL Java_la411_eeg_svm_Feature_Slope_1Sign_1Change
  (JNIEnv *, jclass, jint, jfloatArray, jfloat);

/*
 * Class:     la411_eeg_svm_Feature
 * Method:    writeFeatureInFile
 * Signature: (Ljava/lang/String;FFFFFLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_la411_eeg_svm_Feature_writeFeatureInFile
  (JNIEnv *, jclass, jstring, jfloat, jfloat, jfloat, jfloat, jfloat, jstring);

/*
 * Class:     la411_eeg_svm_Feature
 * Method:    writeFeatureFile
 * Signature: (Ljava/lang/String;FLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_la411_eeg_svm_Feature_writeFeatureFile
  (JNIEnv *, jclass, jstring, jfloat, jstring);

/*
 * Class:     la411_eeg_svm_Feature
 * Method:    writeFileTrainingSet
 * Signature: (Ljava/lang/String;FFLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_la411_eeg_svm_Feature_writeFileTrainingSet
  (JNIEnv *, jclass, jstring, jfloat, jstring);

#ifdef __cplusplus
}
#endif
#endif
